"use client";

import type { GraphEdgeData, GraphNodeData } from "@/lib/types";

type Props = {
  node: GraphNodeData | null;
  edge: GraphEdgeData | null;
};

export default function ImpactPanel({ node, edge }: Props) {
  return (
    <aside className="briefing">
      {!node && !edge && (
        <p className="briefing-empty">
          <strong>Read the sky.</strong>
          Select an event for its briefing, or a connecting line to see why the model believes one
          drives the other.
        </p>
      )}

      {edge && (
        <>
          <h3>Why these are linked</h3>
          <p>{edge.explanation ?? "No explanation recorded."}</p>
          {edge.strength != null && (
            <p className="mono-meta" style={{ marginTop: "1rem" }}>
              Strength {edge.strength.toFixed(2)} · verified
            </p>
          )}
        </>
      )}

      {node && (
        <>
          <p className="label">{node.domain ?? "source unknown"}</p>
          <h2>{node.title}</h2>

          {node.summary?.executive_summary && (
            <>
              <h3>Executive summary</h3>
              <p>{node.summary.executive_summary}</p>
            </>
          )}

          {node.insight?.eventSummary && (
            <>
              <h3>What is happening</h3>
              <p>{node.insight.eventSummary}</p>
            </>
          )}

          {node.insight?.predictions?.length ? (
            <>
              <h3>Where it goes next</h3>
              {node.insight.predictions.map((prediction, index) => (
                <div className="forecast" key={index}>
                  <div className="forecast-horizon">
                    {prediction.horizon}
                    {prediction.confidence != null && (
                      <span>conf. {prediction.confidence.toFixed(2)}</span>
                    )}
                  </div>
                  <p>{prediction.claim}</p>
                </div>
              ))}
            </>
          ) : null}

          {node.url && (
            <p style={{ marginTop: "1.6rem" }}>
              <a href={node.url} target="_blank" rel="noopener noreferrer" className="link-out" style={{ color: "var(--ember)", borderColor: "rgba(233,180,76,0.4)" }}>
                Read the source
                <svg width="9" height="9" viewBox="0 0 9 9" fill="none" aria-hidden="true">
                  <path d="M2 7 7 2M3.4 2H7v3.6" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </a>
            </p>
          )}
        </>
      )}

      <p className="disclaimer">
        Connections, summaries and predictions on this page are generated by AI and may be
        inaccurate. Verify against the linked sources before relying on them.
      </p>
    </aside>
  );
}
