# Generated by Django 6.0.2 on 2026-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('domain', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"news"."apercu"',
            },
        ),
    ]
