# Generated by Django 6.0.2 on 2026-02-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_articles',
            },
        ),
    ]
